version: "3"

services:
  dev:
    build: 
      context: ./devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - datanode2
      - resourcemanager
    tty: true        
    stdin_open: true 
    command: sleep infinity  

  namenode:
    image: rgreen13/hadoop-namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      # Example for mounting an external directory as a volume
      - ./:/Workspace
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: rgreen13/hadoop-datanode
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864

  datanode2:
    image: rgreen13/hadoop-datanode
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ports:
      - 9865:9864

    
  # datanode2:
  #   build: ./datanode
  #   container_name: datanode2
  #   depends_on:
  #     - namenode
  #   volumes:
  #     - hadoop_datanode2:/hadoop/dfs/data
  #   env_file:
  #     - ./hadoop.env
  
  
  resourcemanager:
    image: rgreen13/hadoop-resourcemanager
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864 "
    ports:
      - 8032:8032
      - 8088:8088
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: rgreen13/hadoop-nodemanager
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: rgreen13/hadoop-historyserver
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_datanode2:
  hadoop_historyserver:
